### ISSUE TITLE
Program extracts "ogg.import" files[Bug]: 

### ISSUE THREAD

**Issue by VyzerMusic** [DmitriySalnikov/GodotPCKExplorer#11]
### Commit or version

1.3.3

### On which operating systems the error occurs

Windows 10

### Issue description

I was extracting the pak file for the game "Greener Grass Awaits", and when extracting the audio files, they are all "ogg.import" files that are all 1kb in size. And I've tried many ways to try to open/convert them, but no luck.

### Steps to reproduce

1. Open the GREENERGRASSAWAITS.pck
2. Extract the audio files (I did extract all, the audio files are located in the "music" and "sfx" folders
3. Every single audio file has "ogg.import" at the end, and the file is not openable

**Comment by DmitriySalnikov** [comment]
I found another problem: each `.import` has a `\0` at the end, which should not be there (or not? I'm not sure).
![image](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/e2255f86-a87e-4fd0-9a9f-0509f05aea3b)

Anyway, if you mean that `*.ogg.import` does not open as audio files, then this is the correct behavior. These files are simply redirected to the `.godot/mported` folder. Look at the line `path=`

**Comment by VyzerMusic** [comment]
Ah alright, I now see the correct audio files (for example "fadeOut.ogg-9b5f8b2fddecda09bd50f96cddf26703.oggvorbisstr"), so how do I access these audio files and make them playable?

**Comment by VyzerMusic** [comment]
So do you know of any way to make them playable at all then? doesn't have to be .ogg, is it possible?

**Comment by DmitriySalnikov** [comment]
Most likely, this project will help https://github.com/bruvzg/gdsdecomp

**Comment by VyzerMusic** [comment]
Alright, I'll check it out, thanks!

**Comment by VyzerMusic** [comment]
Sorry if this isn't allowed, but a week ago I also asked someone about this on a different program, and they've successfully implemented this feature [https://github.com/bruvzg/gdsdecomp/releases/tag/v0.6.0](url)

**Comment by DmitriySalnikov** [comment]
I'm not sure what exactly they do for this, but at least their implementation of the program is a module for the engine. That is, they can use the engine code or copy it from other versions of the engine.
My program is written from scratch in C# (when Godot is written in C++), I can't just copy the code from the engine.

But I've already looked at what can be done for decoding and maybe someday I'll add support for some formats.

**Comment by VyzerMusic** [comment]
Ah interesting, thanks for the info!
