### ISSUE TITLE
[Bug]: "GodotPCKExplorer.Console.exe -p" requires encryption key

### ISSUE THREAD

**Issue by twiz-git** [DmitriySalnikov/GodotPCKExplorer#15]
### Commit or version

1.4.0

### On which operating systems the error occurs

Windows

### Issue description

`GodotPCKExplorer.Console.exe -p "D:\Downloads\TestGame\unpacked" "D:\Downloads\TestGame\test.pck" 1.3.3.3`
```
[03/12/2024 23:02:23]   Pack PCK started
[03/12/2024 23:02:23]   Output file: D:\Downloads\TestGame\test.pck
[03/12/2024 23:02:23]   [Error] "Error": The encryption key is not specified, although the encryption mode is activated.
```
Unpacking with the `-e` switch works fine.
Packing with the GUI version works fine with the same files, with `Enable Encryption` option unticked.

### Steps to reproduce

N/A

**Comment by DmitriySalnikov** [comment]
Confirmed. The key should not be requested for regular packings.

**Comment by DmitriySalnikov** [comment]
[test binaries](https://github.com/DmitriySalnikov/GodotPCKExplorer/actions/runs/8263731676)
