### ISSUE TITLE
[Bug]: Certain games not working with error "Not a Godot PCK file"

### ISSUE THREAD

**Issue by StickyChannel92** [DmitriySalnikov/GodotPCKExplorer#19]
### Commit or version

1.4.2.0

### On which operating systems the error occurs

Windows

### Issue description

I'm trying to rip assets from a demo on Steam so that I can make fan-art out of them. It is a GoDot game, since it's exe has an icon. Unfortunately, the only thing out of the Dreamed Away demo is the exe and nothing else. No pck is included. I tried to just unpack it but the exe doesn't parse and just quits out.

I tried various tools to get the encryption key, but unfortunately, I keep running into the same issue where the exe won't parse. Ghidra was a learning curve and couldn't get any assets out of it. Same thing with GodotPCKExplorer.
![image](https://github.com/user-attachments/assets/6f4d6463-2e81-44bb-945f-2b3b46fa7488)

### Steps to reproduce

N/A

**Comment by DmitriySalnikov** [comment]
And `GodotPCKExplorer` is right. The developers of this game decided to add problems when trying to unpack game resources.
They replaced the standard `PCK` file start and end marker from `GDPC` to `wGPC`. That is, now it is not a standard `PCK` file and cannot be read by other versions of Godot and other programs for working with PCK files.
![image](https://github.com/user-attachments/assets/7acfadfb-0ac1-4f1c-a4b7-8fe3be2da63b)

I don't know if it's worth trying to add a mode with support for such conditions to PCK Explorer at all 🤷‍♂️


> I'm trying to rip assets from a demo on Steam so that I can make fan-art out of them.

But considering your task, I can recommend my [Image Extractor](https://github.com/DmitriySalnikov/PNG_Extractor)

![image](https://github.com/user-attachments/assets/5e31c5b4-5208-4cb1-9272-88f6810a5daf)
![236](https://github.com/user-attachments/assets/79ec5da2-3d6d-4870-ab27-6556b5bc504a)

**Comment by StickyChannel92** [comment]
Thanks for the help! It sucks that developers do stuff like this for data miners, especially sprite rippers for stuff on The Spriters Resource. I may use the linked tool for future use.
Closing issue now.
