### ISSUE TITLE
[Bug]: patching not shown in ui

### ISSUE THREAD

**Issue by beatrixwashere** [DmitriySalnikov/GodotPCKExplorer#21]
### Commit or version

1.4.2

### On which operating systems the error occurs

Windows

### Issue description

patching files into an existing pck is showcased in the readme but isn't present in the binaries, and although they may not be updated yet i'm not sure how to build the repo myself to get access to the features

### Steps to reproduce

- use the pack or embed folder option in the ui
- the "patching" and "enabled patching" options are not shown at the top

**Comment by DmitriySalnikov** [comment]
I just updated the program and screenshots yesterday, and the patching has already been noticed 😅. [Here](https://github.com/DmitriySalnikov/GodotPCKExplorer/actions/runs/11468789536) you can download the latest version.

But I don't know yet how to do it better: leave the creation of a "patched PCK with a different name" as it is now, or update the selected PCK with new files?

**Comment by beatrixwashere** [comment]
thanks for the quick response! i downloaded the latest version and it's working so far :]

on the question, i think it might be better to create a patched pck with a different name as it is, since the user can keep the original as a backup or override it as an option to update it
