### ISSUE TITLE
[Bug]: PCK Bruteforcer doesn't work for Godot 4.2.2 upwards

### ISSUE THREAD

**Issue by JanWerder** [DmitriySalnikov/GodotPCKExplorer#23]
### Commit or version

Bruteforcer 1.0.1

### On which operating systems the error occurs

Windows

### Issue description

I've tried to bruteforce a sample project with godot 4.2.2 and it doesn't find the key.
Here is the reproducible example:
[test-enc.console.zip](https://github.com/user-attachments/files/17899006/test-enc.console.zip)
Key: 491E1CED13F589AC9670164CD34C6DA454D3E3C16944D5C8E2996A7DD50B3BDD

### Steps to reproduce

Start the Bruteforce from 0 to 69161984.
Let it run 
> No matching key found

### Logs

N/A

**Comment by DmitriySalnikov** [comment]
I can't run this project. Neither the original files, nor the repacked ones without encryption.

![image](https://github.com/user-attachments/assets/1e28b72c-f7a4-4e2f-8366-62d3015c3985)
![image](https://github.com/user-attachments/assets/f10ec812-88da-4fa0-a5a2-019b30bf310c)

**Comment by JanWerder** [comment]
You are correct, I haven't recompiled the export templates. After doing that I could recover the key. Thanks for looking into it.
