### ISSUE TITLE
Add Godot 4.x support

### ISSUE THREAD

**Issue by DmitriySalnikov** [DmitriySalnikov/GodotPCKExplorer#3]
It looks like PCK has been changed in Godot 4.

**Comment by nikitalita** [comment]
Indeed. They broke backwards compatibility and added two fields before the reserved fields, changing the header length. You can check how we handle it in GDRE tools here: https://github.com/bruvzg/gdsdecomp/blob/master/utility/gdre_packed_source.cpp#L192

**Comment by DmitriySalnikov** [comment]
It turned out to be a bit more complicated than just two new fields, but now I hope PCK Explorer supports Godot 4 PCK files.
