### ISSUE TITLE
[Bug]: Create pck function is broken in 1.3.1

### ISSUE THREAD

**Issue by AG-w** [DmitriySalnikov/GodotPCKExplorer#5]
### Commit or version

1.3.1

### On which operating systems the error occurs

Windows

### Issue description

When you click "Pack or Embed folder", the program just frozen and do nothing

go back to 1.3.0 and it works fine

### Steps to reproduce

1. click "Pack or Embed folder"
2. stuck at empty progress bar forever

**Comment by DmitriySalnikov** [comment]
I can only get errors if I don't delete the old files before updating.
![image](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/eae7dd8c-7670-445c-ba1c-15a075c36e25)
But I don't have any errors if I use the clean version 1.3.1

**Comment by AG-w** [comment]
so after I use 1.3.0 to pack a pck file, 1.3.1 no longer frozen at progress bar

I noticed you added a progress bar here, but there's no progress bar in 1.3.0
https://github.com/DmitriySalnikov/GodotPCKExplorer/commit/2ec24aeda88780b173a7823a22ae2d3561114a08#diff-b6a8b961aeb93b8aad9caab9c75941d3590510c5dec91e3b8c024000c6e51c54

This is just my assumption
what if you use Create pck function for the first time, that FolderPath never get initialized and it stuck at scanning empty path?

**Comment by DmitriySalnikov** [comment]
Fixed in 55420947dc371f0ee41911184110aac891361af6
https://github.com/DmitriySalnikov/GodotPCKExplorer/actions/runs/6472746869
