### ISSUE TITLE
[Bug]:  console command not work

### ISSUE THREAD

**Issue by wesamdev** [DmitriySalnikov/GodotPCKExplorer#7]
### Commit or version

1.3.3

### On which operating systems the error occurs

Windows

### Issue description

console command not work when type `GodotPCKExplorer.UI.exe -h`it return nothing

### Steps to reproduce

N/A

**Comment by DmitriySalnikov** [comment]
Most likely it will be fixed in this build: https://github.com/DmitriySalnikov/GodotPCKExplorer/actions/runs/6841678020

But also this update contains a complete migration to NET 6, which I have not yet published in `Releases`.

**Comment by wesamdev** [comment]
program not open

**Comment by DmitriySalnikov** [comment]
did you see something like that?
![2EgXc.png](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/296bf934-15c9-4f14-96e8-6ca2d2fb72d2)

or another error?

**Comment by DmitriySalnikov** [comment]
did you see something like that?
![2EgXc.png](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/296bf934-15c9-4f14-96e8-6ca2d2fb72d2)
if yes, then as it says there, you need to install .NET Desktop
![Screenshot_20231112_231320_com.yandex.browser.png](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/07403a29-ede4-45a8-8607-ae0b4e7c6cc2)


or some another error?

**Comment by wesamdev** [comment]
works
